# Generated by Django 3.0.6 on 2020-05-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hours_assigned',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
