# Generated by Django 3.0.6 on 2020-05-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_student_hours_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hours_assigned',
            field=models.IntegerField(default=0),
        ),
    ]
