# Generated by Django 3.0.6 on 2020-05-18 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20200518_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Shift')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='shifts',
            field=models.ManyToManyField(through='control.StudentShift', to='control.Shift'),
        ),
    ]
