# Generated by Django 3.0.6 on 2020-05-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20200518_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='shifts',
            field=models.ManyToManyField(to='control.Shift'),
        ),
        migrations.DeleteModel(
            name='StudentShift',
        ),
    ]
